# SPDX-FileCopyrightText: 2024 Checkraze
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 Maxtone
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2025 Blu
# SPDX-FileCopyrightText: 2025 EctoplasmIsGood
# SPDX-FileCopyrightText: 2025 ScyronX
# SPDX-FileCopyrightText: 2025 Your Name
# SPDX-FileCopyrightText: 2025 dustylens
# SPDX-FileCopyrightText: 2025 mikusssssss
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: DirectorOfCare
  name: job-name-doc
  description: job-description-doc
  playTimeTracker: JobDirectorOfCare
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 162000 # mono - 45 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 72000 # mono - 20 hours
  alternateRequirementSets: # mono
    longerPlaytimeLessSec: # mono
    - !type:OverallPlaytimeRequirement # mono
      time: 234000 # mono 65 hours
  startingGear: DocGear
  alwaysUseSpawner: true
  icon: "JobIconDoc"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 170
  displayWeight: 60 # Second from the top # mono - first from top
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: NpcFactionMember
        factions:
        - MD # mono faction
      - type: SurgerySpeedModifier
        SpeedModifier: 2
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: DocGear
  equipment:
    pocket1: HypoMini
    pocket2: MedicalAppraisalTool
  storage:
    back:
    - RubberStampDoc
    - BoxFolderMedicalDoctor
    - StationAdministrationConsoleFlatpack
