# SPDX-FileCopyrightText: 2025 Southbridge
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: MarkerBase
  id: DecalSpawnerBase
  name: Decal Spawner
  abstract: true
  components:
  - type: Sprite
    layers:
    - state: green
    - state: decal
