# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: MonoAISTCShuttleSpawnerScheduler
  parent: BaseGameRule
  components:
    - type: BasicStationEventScheduler
      scheduledGameRules: !type:NestedSelector
        tableId: DamagedAIShipsTable
      minimumTimeUntilFirstEvent: 3600 # 60 minutes
      minMaxEventTiming:
        min: 5400 # 90 minutes between events
        max: 7200 # 120 minutes between events

- type: entity
  id: MonoAISTCShuttleSpawnerSchedulerTier2
  parent: BaseGameRule
  components:
  - type: BasicStationEventScheduler
    scheduledGameRules: !type:NestedSelector
      tableId: DamagedAIShipsTableT2
    minimumTimeUntilFirstEvent: 18000 # 5 hours
    minMaxEventTiming:
      min: 3600 # 60 minutes between events
      max: 3600 # 60 minutes between events

- type: entity
  id: MonoAsakimSTCShuttleSpawnerScheduler
  parent: BaseGameRule
  components:
  - type: BasicStationEventScheduler
    scheduledGameRules: !type:NestedSelector
      tableId: AsakimShipsTable
    minimumTimeUntilFirstEvent: 10800 # 180 minutes
    minMaxEventTiming:
      min: 3600 # 60 minutes between events
      max: 7200 # 120 minutes between events

- type: entity
  abstract: true
  parent: BaseGameRule
  id: BaseRandomShuttleRule
  components:
  - type: StationEvent
    weight: 10
    reoccurrenceDelay: 30
    duration: 1
    maxOccurrences: 2 # should be the same as [copies] in ship_spawns.yml
  - type: RuleGrids
  - type: LoadMapRule
