# SPDX-FileCopyrightText: 2022 metalgearsloth
# SPDX-FileCopyrightText: 2022 mirrorcult
# SPDX-FileCopyrightText: 2023 Kevin Zheng
# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 TsjipTsjip
# SPDX-FileCopyrightText: 2025 Redrover1760
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
