# SPDX-FileCopyrightText: 2023 Debug
# SPDX-FileCopyrightText: 2025 Redrover1760
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Publish Changelog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
 publish_changelog:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        ref: main

    - name: Publish changelog
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}
    continue-on-error: true
